env:
  browser: true

extends:
  airbnb-base

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

# very basic javascript
parserOptions:
  ecmaVersion: 5
  sourceType: script

ignorePatterns:
  - node_modules/
  - public/vendor/

rules:
  # some javascript functions are used within html attributes rendered within php
  no-unused-vars: off

  max-len: off

  # yeah, we're polluting the global namespace with jquery...
  no-undef: off

  # ouch. refactor affected code...
  no-eval: off

  # let's at least have console output. at least no alerts, right? right!?
  no-console: off

  # ++ in for loop
  no-plusplus: off

  # ecmaVersion 5...
  comma-dangle: off
  no-alert: off # still using confirm() dialog
  no-loop-func: off
  no-param-reassign: off
  no-var: off
  object-shorthand: off
  prefer-arrow-callback: off
  prefer-rest-params: off
  prefer-template: off

  func-names: off
  no-useless-escape: off # not so sure about regex there it seems
  no-use-before-define: off
  vars-on-top: off
