<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Game;
use App\Platform\Actions\ComputeGameSortTitleAction;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Game>
 */
class GameFactory extends Factory
{
    protected $model = Game::class;

    private static int $sequence = 1;

    /**
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Use a sequence to ensure unique titles and stave off test flake.
        $title = ucwords(fake()->words(2, true) . ' ' . self::$sequence++);

        return [
            'Title' => $title,
            'sort_title' => null,
            'ConsoleID' => 0,
            'ImageIcon' => '/Images/000001.png',
            'RichPresencePatch' => fake()->words(10, true),
        ];
    }

    public function configure(): static
    {
        /**
         * Derive the sort_title from both autogenerated and manually-provided titles.
         * If the factory receives a custom sort_title, do nothing.
         */

        return $this->afterMaking(function (Game $game) {
            if ($game->sort_title === null) {
                $game->sort_title = (new ComputeGameSortTitleAction())->execute($game->title);
            }
        })->afterCreating(function (Game $game) {
            if ($game->sort_title === null) {
                $game->sort_title = (new ComputeGameSortTitleAction())->execute($game->title);
            }
        });
    }
}
