<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\Permissions;
use App\Models\User;
use App\Support\Database\Eloquent\Concerns\FakesUsername;
use Exception;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends Factory<User>
 */
class UserFactory extends Factory
{
    use FakesUsername;

    protected $model = User::class;

    /**
     * @throws Exception
     */
    public function definition(): array
    {
        return [
            // required
            'ulid' => (string) Str::ulid(),
            'username' => $this->fakeUsername(),
            'display_name' => null,
            'email' => fake()->unique()->safeEmail,
            'email_verified_at' => now(),
            'Permissions' => Permissions::Registered,
            'password' => Hash::make('password'),
            'legacy_salted_password' => '',
            'points_hardcore' => fake()->numberBetween(0, 9999) * 10,
            'points' => 0,
            'points_weighted' => 0,
            'yield_unlocks' => 0,
            'delete_requested_at' => null,
            'unread_messages' => 0,
            'is_user_wall_active' => 1,
            'muted_until' => null,
            'visible_role_id' => null,
            'preferences_bitfield' => 0,

            // nullable
            'web_api_key' => 'apiKey',
            'remember_token' => Str::random(10),
            'banned_at' => null,
        ];
    }

    public function configure(): static
    {
        /**
         * Derive the display_name from both autogenerated and manually-provided usernames.
         * If the factory receives a custom display_name, do nothing.
         */

        return $this->afterMaking(function (User $user) {
            if ($user->display_name === null) {
                $user->display_name = $user->username;
            }
        })->afterCreating(function (User $user) {
            if ($user->display_name === null) {
                $user->display_name = $user->username;
            }
        });
    }

    public function unverified(): static
    {
        return $this->state(fn (array $attributes) => [
            // 'email_verified_at' => null,
            'Permissions' => Permissions::Unregistered,
        ]);
    }

    public function untracked(): static
    {
        return $this->state(fn (array $attributes) => [
            'unranked_at' => now(),
        ]);
    }
}
