/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "forum.post.edit": [
        {
            "name": "forumTopicComment",
            "required": true,
            "binding": "ID"
        }
    ],
    "forum-topic.create": [
        {
            "name": "forum",
            "required": true,
            "binding": "ID"
        }
    ],
    "forum.recent-posts": [],
    "demo": [],
    "demo.error": [
        {
            "name": "code",
            "required": true
        }
    ],
    "home": [],
    "tickets.index": [],
    "tickets.most-reported-games": [],
    "ranking.beaten-games": [],
    "message-thread.index": [],
    "message.create": [],
    "achievement.tickets": [
        {
            "name": "achievement",
            "required": true,
            "binding": "ID"
        }
    ],
    "achievement.create-ticket": [
        {
            "name": "achievement",
            "required": true,
            "binding": "ID"
        }
    ],
    "achievement.report-issue": [
        {
            "name": "achievement",
            "required": true,
            "binding": "ID"
        }
    ],
    "achievement.comments": [
        {
            "name": "achievement",
            "required": true,
            "binding": "ID"
        }
    ],
    "redirect": [],
    "developer.tickets": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "reporter.tickets": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "developer.tickets.resolved-for-others": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "developer.feed": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "developer.claims": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "developer.sets": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "user.comments": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "user.posts": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "user.game.activity": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        },
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.compare-unlocks": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        },
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "user.moderation-comments": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "user.completion-progress": [
        {
            "name": "user",
            "required": true,
            "binding": "User"
        }
    ],
    "leaderboard.comments": [
        {
            "name": "leaderboard",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.random": [],
    "game.hash": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.hash.manage": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.hashes.comments": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.tickets": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.comments": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.dev-interest": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.modification-comments": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.suggest": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "game.claims.comments": [
        {
            "name": "game",
            "required": true,
            "binding": "ID"
        }
    ],
    "system.game.index": [
        {
            "name": "system",
            "required": true,
            "binding": "ID"
        }
    ],
    "rss.index": [],
    "ticket.show": [
        {
            "name": "ticket",
            "required": true,
            "binding": "ID"
        }
    ],
    "message-thread.show": [
        {
            "name": "messageThread",
            "required": true,
            "binding": "id"
        }
    ],
    "terms": [],
    "games.suggest": [],
    "contact": [],
    "claims.index": [],
    "claims.expiring": [],
    "claims.completed": [],
    "claims.active": [],
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.pages.tools": [],
    "filament.admin.resources.achievements.index": [],
    "filament.admin.resources.achievements.create": [],
    "filament.admin.resources.achievements.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.achievements.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.achievements.audit-log": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.game-hashes.index": [],
    "filament.admin.resources.games.index": [],
    "filament.admin.resources.games.create": [],
    "filament.admin.resources.games.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.games.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.games.audit-log": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.roles.index": [],
    "filament.admin.resources.roles.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.systems.index": [],
    "filament.admin.resources.systems.create": [],
    "filament.admin.resources.systems.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.systems.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.systems.audit-log": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.roles": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.audit-log": [
        {
            "name": "record",
            "required": true
        }
    ],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "log-viewer.hosts": [],
    "log-viewer.folders": [],
    "log-viewer.folders.request-download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.clear-cache": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.folders.delete": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files": [],
    "log-viewer.files.request-download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.delete": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.clear-cache-all": [],
    "log-viewer.files.delete-multiple-files": [],
    "log-viewer.logs": [],
    "log-viewer.folders.download": [
        {
            "name": "folderIdentifier",
            "required": true
        }
    ],
    "log-viewer.files.download": [
        {
            "name": "fileIdentifier",
            "required": true
        }
    ],
    "log-viewer.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "game-hash.update": [
        {
            "name": "gameHash",
            "required": true,
            "binding": "hash"
        }
    ],
    "game-hash.destroy": [
        {
            "name": "gameHash",
            "required": true,
            "binding": "hash"
        }
    ],
    "forum.recent-posts2": [],
    "message.store": [],
    "message-thread.destroy": [
        {
            "name": "messageThread",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "logout": [],
    "password.confirmation": [],
    "password.confirm": [],
    "download.index": [],
    "game.index": [],
    "user.show": [
        {
            "name": "user",
            "required": true
        }
    ],
    "achievement.show": [
        {
            "name": "achievement",
            "required": true
        },
        {
            "name": "slug",
            "required": false
        }
    ],
    "game.show": [
        {
            "name": "game",
            "required": true
        },
        {
            "name": "slug",
            "required": false
        }
    ],
    "leaderboard.show": [
        {
            "name": "leaderboard",
            "required": true
        },
        {
            "name": "slug",
            "required": false
        }
    ],
    "user.permalink": [
        {
            "name": "hashId",
            "required": true
        }
    ],
    "laravel-folio": [
        {
            "name": "fallbackPlaceholder",
            "required": true
        }
    ]
}
}
export {};
