ALTER TABLE GameAlternatives DEFAULT COLLATE latin1_general_ci;
ALTER TABLE PlaylistVideo DEFAULT COLLATE latin1_general_ci;
ALTER TABLE PlaylistVideo CONVERT TO CHARACTER SET latin1 COLLATE latin1_general_ci;
ALTER TABLE Rating DEFAULT COLLATE latin1_general_ci;
ALTER TABLE Rating CONVERT TO CHARACTER SET latin1 COLLATE latin1_general_ci;
ALTER TABLE ScoreHistory DEFAULT COLLATE latin1_general_ci;
ALTER TABLE ScoreHistory CONVERT TO CHARACTER SET latin1 COLLATE latin1_general_ci;
ALTER TABLE SetRequest DEFAULT COLLATE latin1_general_ci;
ALTER TABLE SiteAwards DEFAULT COLLATE latin1_general_ci;
ALTER TABLE SiteAwards CONVERT TO CHARACTER SET latin1 COLLATE latin1_general_ci;
ALTER TABLE Ticket DEFAULT COLLATE latin1_general_ci;
ALTER TABLE Ticket CONVERT TO CHARACTER SET latin1 COLLATE latin1_general_ci;
