ALTER TABLE GameData ADD COLUMN CoreAchievementCount int(11) NOT NULL DEFAULT 0;
ALTER TABLE GameData ADD COLUMN Points int(11) NOT NULL DEFAULT 0;
ALTER TABLE GameData ADD COLUMN LeaderboardCount int(11) NOT NULL DEFAULT 0;
ALTER TABLE GameData ADD COLUMN PlayerCount int(11) NOT NULL DEFAULT 0;
ALTER TABLE GameData ADD COLUMN MetricsUpdated timestamp NULL;
