<?php

/*
 * Note: used for seeding
 */
return [
    1 => [
        'name' => 'Mega Drive / Genesis',
        'name_full' => 'Sega Mega Drive / Genesis',
        'name_short' => 'MD',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    2 => [
        'name' => 'Nintendo 64',
        'name_full' => 'Nintendo 64',
        'name_short' => 'N64',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    3 => [
        'name' => 'SNES',
        'name_full' => 'Super Nintendo Entertainment System',
        'name_short' => 'SNES',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    4 => [
        'name' => 'Game Boy',
        'name_full' => 'Nintendo Game Boy',
        'name_short' => 'GB',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    5 => [
        'name' => 'Game Boy Advance',
        'name_full' => 'Nintendo Game Boy Advance',
        'name_short' => 'GBA',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    6 => [
        'name' => 'Game Boy Color',
        'name_full' => 'Nintendo Game Boy Color',
        'name_short' => 'GBC',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    7 => [
        'name' => 'NES',
        'name_full' => 'Nintendo Entertainment System',
        'name_short' => 'NES',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    8 => [
        'name' => 'PC Engine / TurboGrafx',
        'name_full' => 'NEC PC Engine / TurboGrafx',
        'name_short' => 'PCE',
        'manufacturer' => 'NEC',
        'active' => true,
    ],
    9 => [
        'name' => 'Sega CD',
        'name_full' => 'Sega CD',
        'name_short' => 'SCD',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    10 => [
        'name' => '32X',
        'name_full' => 'Sega 32X',
        'name_short' => '32X',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    11 => [
        'name' => 'Master System',
        'name_full' => 'Sega Master System',
        'name_short' => 'SMS',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    12 => [
        'name' => 'PlayStation',
        'name_full' => 'Sony PlayStation',
        'name_short' => 'PS1',
        'manufacturer' => 'Sony',
        'active' => true,
    ],
    13 => [
        'name' => 'Lynx',
        'name_full' => 'Atari Lynx',
        'name_short' => 'Lynx',
        'manufacturer' => 'Atari',
        'active' => true,
    ],
    14 => [
        'name' => 'Neo Geo Pocket',
        'name_full' => 'SNK Neo Geo Pocket',
        'name_short' => 'NGP',
        'manufacturer' => 'SNK',
        'active' => true,
    ],
    15 => [
        'name' => 'Game Gear',
        'name_full' => 'Sega Game Gear',
        'name_short' => 'GG',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    16 => [
        'name' => 'GameCube',
        'name_full' => 'Nintendo GameCube',
        'name_short' => 'GC',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    17 => [
        'name' => 'Jaguar',
        'name_full' => 'Atari Jaguar',
        'name_short' => 'JAG',
        'manufacturer' => 'Atari',
        'active' => true,
    ],
    18 => [
        'name' => 'DS',
        'name_full' => 'Nintendo DS',
        'name_short' => 'DS',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    19 => [
        'name' => 'Wii',
        'name_full' => 'Nintendo Wii',
        'name_short' => 'Wii',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    20 => [
        'name' => 'Wii U',
        'name_full' => 'Nintendo Wii U',
        'name_short' => 'WiiU',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    21 => [
        'name' => 'PlayStation 2',
        'name_full' => 'Sony PlayStation 2',
        'name_short' => 'PS2',
        'manufacturer' => 'Sony',
        'active' => true,
    ],
    22 => [
        'name' => 'Xbox',
        'name_full' => 'Microsoft Xbox',
        'name_short' => 'Xbox',
        'manufacturer' => 'Microsoft',
        'active' => false,
    ],
    23 => [
        'name' => 'Odyssey 2',
        'name_full' => 'Magnavox Odyssey 2',
        'name_short' => 'MO2',
        'manufacturer' => 'Magnavox',
        'active' => true,
    ],
    24 => [
        'name' => 'Pokemon Mini',
        'name_full' => 'Nintendo Pokemon Mini',
        'name_short' => 'MINI',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    25 => [
        'name' => 'Atari 2600',
        'name_full' => 'Atari 2600',
        'name_short' => '2600',
        'manufacturer' => 'Atari',
        'active' => true,
    ],
    26 => [
        'name' => 'DOS',
        'name_full' => 'DOS',
        'name_short' => 'DOS',
        'manufacturer' => null,
        'active' => false,
    ],
    27 => [
        'name' => 'Arcade',
        'name_full' => 'Arcade',
        'name_short' => 'ARC',
        'manufacturer' => null,
        'active' => true,
    ],
    28 => [
        'name' => 'Virtual Boy',
        'name_full' => 'Nintendo Virtual Boy',
        'name_short' => 'VB',
        'manufacturer' => 'Nintendo',
        'active' => true,
    ],
    29 => [
        'name' => 'MSX',
        'name_full' => 'Microsoft MSX',
        'name_short' => 'MSX',
        'manufacturer' => 'Microsoft',
        'active' => true,
    ],
    30 => [
        'name' => 'Commodore 64',
        'name_full' => 'Commodore 64',
        'name_short' => 'C64',
        'manufacturer' => 'Commodore',
        'active' => false,
    ],
    31 => [
        'name' => 'ZX81',
        'name_full' => 'Sinclair ZX81',
        'name_short' => 'ZX81',
        'manufacturer' => 'Sinclair',
        'active' => false,
    ],
    32 => [
        'name' => 'Oric',
        'name_full' => 'TCS Oric',
        'name_short' => 'Oric',
        'manufacturer' => 'TCS', // Tangerine Computer Systems is just too long and not significant enough to hold the full name
        'active' => false,
    ],
    33 => [
        'name' => 'SG-1000',
        'name_full' => 'Sega SG-1000',
        'name_short' => 'SG1K',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    34 => [
        'name' => 'VIC-20',
        'name_full' => 'Commodore VIC-20',
        'name_short' => 'VIC-20',
        'manufacturer' => 'Commodore',
        'active' => false,
    ],
    35 => [
        'name' => 'Amiga',
        'name_full' => 'Commodore Amiga',
        'name_short' => 'Amiga',
        'manufacturer' => 'Commodore',
        'active' => false,
    ],
    36 => [
        'name' => 'Atari ST',
        'name_full' => 'Atari ST',
        'name_short' => 'AST',
        'manufacturer' => 'Atari',
        'active' => false,
    ],
    37 => [
        'name' => 'CPC',
        'name_full' => 'Amstrad CPC',
        'name_short' => 'CPC',
        'manufacturer' => 'Amstrad',
        'active' => true,
    ],
    38 => [
        'name' => 'Apple II',
        'name_full' => 'Apple II',
        'name_short' => 'A2',
        'manufacturer' => 'Apple',
        'active' => true,
    ],
    39 => [
        'name' => 'Saturn',
        'name_full' => 'Sega Saturn',
        'name_short' => 'SAT',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    40 => [
        'name' => 'Dreamcast',
        'name_full' => 'Sega Dreamcast',
        'name_short' => 'DC',
        'manufacturer' => 'Sega',
        'active' => true,
    ],
    41 => [
        'name' => 'Playstation Portable',
        'name_full' => 'Sony PlayStation Portable',
        'name_short' => 'PSP',
        'manufacturer' => 'Sony',
        'active' => true,
    ],
    42 => [
        'name' => 'CD-i',
        'name_full' => 'Philips CD-i',
        'name_short' => 'CD-i',
        'manufacturer' => 'Philips',
        'active' => false,
    ],
    43 => [
        'name' => '3DO Interactive Multiplayer',
        'name_full' => '3DO Interactive Multiplayer',
        'name_short' => '3DO',
        'manufacturer' => '3DO', // The 3DO Company is too long
        'active' => true,
    ],
    44 => [
        'name' => 'ColecoVision',
        'name_full' => 'ColecoVision',
        'name_short' => 'CV',
        'manufacturer' => 'Coleco',
        'active' => true,
    ],
    45 => [
        'name' => 'Intellivision',
        'name_full' => 'Mattel Intellivision',
        'name_short' => 'INTV',
        'manufacturer' => 'Mattel',
        'active' => true,
    ],
    46 => [
        'name' => 'Vectrex',
        'name_full' => 'GCE Vectrex',
        'name_short' => 'VECT',
        'manufacturer' => 'GCE',
        'active' => true,
    ],
    47 => [
        'name' => 'PC-8000/8800',
        'name_full' => 'NEC PC-8000/8800',
        'name_short' => '80/88',
        'manufacturer' => 'NEC',
        'active' => true,
    ],
    48 => [
        'name' => 'PC-9800',
        'name_full' => 'NEC PC-9800',
        'name_short' => '9800',
        'manufacturer' => 'NEC',
        'active' => false,
    ],
    49 => [
        'name' => 'PC-FX',
        'name_full' => 'NEC PC-FX',
        'name_short' => 'PC-FX',
        'manufacturer' => 'NEC',
        'active' => true,
    ],
    50 => [
        'name' => 'Atari 5200',
        'name_full' => 'Atari 5200',
        'name_short' => '5200',
        'manufacturer' => 'Atari',
        'active' => false,
    ],
    51 => [
        'name' => 'Atari 7800',
        'name_full' => 'Atari 7800',
        'name_short' => '7800',
        'manufacturer' => 'Atari',
        'active' => true,
    ],
    52 => [
        'name' => 'X68000',
        'name_full' => 'Sharp X68000',
        'name_short' => 'X68K',
        'manufacturer' => 'Sharp',
        'active' => false,
    ],
    53 => [
        'name' => 'WonderSwan',
        'name_full' => 'Bandai WonderSwan',
        'name_short' => 'WS',
        'manufacturer' => 'Bandai',
        'active' => true,
    ],
    54 => [
        'name' => 'Cassette Vision',
        'name_full' => 'Epoch Co. Cassette Vision',
        'name_short' => 'Cassette Vision',
        'manufacturer' => 'Epoch Co.',
        'active' => false,
    ],
    55 => [
        'name' => 'Super Cassette Vision',
        'name_full' => 'Epoch Co. Super Cassette Vision',
        'name_short' => 'Super Cassette Vision',
        'manufacturer' => 'Epoch Co.',
        'active' => false,
    ],
    56 => [
        'name' => 'Neo Geo CD',
        'name_full' => 'SNK Neo Geo CD',
        'name_short' => 'NGCD',
        'manufacturer' => 'SNK',
        'active' => true,
    ],
    57 => [
        'name' => 'Channel F',
        'name_full' => 'Fairchild Channel F',
        'name_short' => 'CHF',
        'manufacturer' => 'Fairchild',
        'active' => true,
    ],
    58 => [
        'name' => 'FM Towns',
        'name_full' => 'Fujitsu FM Towns',
        'name_short' => 'FM Towns',
        'manufacturer' => 'Fujitsu',
        'active' => false,
    ],
    59 => [
        'name' => 'ZX Spectrum',
        'name_full' => 'Sinclair ZX Spectrum',
        'name_short' => 'ZXS',
        'manufacturer' => 'Sinclair',
        'active' => false,
    ],
    60 => [
        'name' => 'Game & Watch',
        'name_full' => 'Nintendo Game & Watch',
        'name_short' => 'G&W',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    61 => [
        'name' => 'N-Gage',
        'name_full' => 'Nokia N-Gage',
        'name_short' => 'N-Gage',
        'manufacturer' => 'Nokia',
        'active' => false,
    ],
    62 => [
        'name' => '3DS',
        'name_full' => 'Nintendo 3DS',
        'name_short' => '3DS',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    63 => [
        'name' => 'Supervision',
        'name_full' => 'Watara Supervision',
        'name_short' => 'WSV',
        'manufacturer' => 'Watara',
        'active' => true,
    ],
    64 => [
        'name' => 'X1',
        'name_full' => 'Sharp X1',
        'name_short' => 'X1',
        'manufacturer' => 'Sharp',
        'active' => false,
    ],
    65 => [
        'name' => 'TIC-80',
        'name_full' => 'TIC-80',
        'name_short' => 'TIC-80',
        'manufacturer' => null,
        'active' => false,
    ],
    66 => [
        'name' => 'TO8',
        'name_full' => 'Thomson TO8',
        'name_short' => 'TO8',
        'manufacturer' => 'Thomson',
        'active' => false,
    ],
    67 => [
        'name' => 'PC-6000',
        'name_full' => 'NEC PC-6000',
        'name_short' => 'PC-6000',
        'manufacturer' => 'NEC',
        'active' => false,
    ],
    68 => [
        'name' => 'Pico',
        'name_full' => 'Sega Pico',
        'name_short' => 'Pico',
        'manufacturer' => 'Sega',
        'active' => false,
    ],
    69 => [
        'name' => 'Mega Duck',
        'name_full' => 'Mega Duck',
        'name_short' => 'DUCK',
        'manufacturer' => 'Welback Holdings',
        'active' => true,
    ],
    70 => [
        'name' => 'Zeebo',
        'name_full' => 'Zeebo',
        'name_short' => 'Zeebo',
        'manufacturer' => 'Zeebo',
        'active' => false,
    ],
    71 => [
        'name' => 'Arduboy',
        'name_full' => 'Arduboy',
        'name_short' => 'ARD',
        'manufacturer' => '',
        'active' => false,
    ],
    72 => [
        'name' => 'WASM-4',
        'name_full' => 'WASM-4',
        'name_short' => 'WASM4',
        'manufacturer' => '',
        'active' => false,
    ],
    73 => [
        'name' => 'Arcadia 2001',
        'name_full' => 'Arcadia 2001',
        'name_short' => 'A2001',
        'manufacturer' => 'Emerson Radio',
        'active' => false,
    ],
    74 => [
        'name' => 'Interton VC 4000',
        'name_full' => 'Interton VC 4000',
        'name_short' => 'VC4000',
        'manufacturer' => 'Interton',
        'active' => false,
    ],
    75 => [
        'name' => 'TV Games Computer',
        'name_full' => 'Elektor TV Games Computer',
        'name_short' => 'ELEK',
        'manufacturer' => 'Elektor',
        'active' => false,
    ],
    76 => [
        'name' => 'PC Engine CD',
        'name_full' => 'NEC PC Engine CD',
        'name_short' => 'PCCD',
        'manufacturer' => 'NEC',
        'active' => false,
    ],
    77 => [
        'name' => 'Jaguar CD',
        'name_full' => 'Atari Jaguar CD',
        'name_short' => 'JCD',
        'manufacturer' => 'Atari',
        'active' => false,
    ],
    78 => [
        'name' => 'Nintendo DSi',
        'name_full' => 'Nintendo DSi',
        'name_short' => 'DSi',
        'manufacturer' => 'Nintendo',
        'active' => false,
    ],
    79 => [
        'name' => 'TI-83',
        'name_full' => 'Texas Instruments TI-83',
        'name_short' => 'TI-83',
        'manufacturer' => 'Texas Instruments',
        'active' => false,
    ],
    80 => [
        'name' => 'Uzebox',
        'name_full' => 'Uzebox',
        'name_short' => 'UZE',
        'manufacturer' => '',
        'active' => false,
    ],
    100 => [
        'name' => 'Hubs',
        'name_full' => null,
        'name_short' => 'hubs',
        'manufacturer' => null,
        'active' => false,
    ],
    101 => [
        'name' => 'Events',
        'name_full' => null,
        'name_short' => 'events',
        'manufacturer' => null,
        'active' => true,
    ],
];
