<?php

use App\Community\Enums\CommentableType;
use App\Community\Enums\SubscriptionSubjectType;
use App\Community\Services\SubscriptionNotificationService;
use App\Community\Services\SubscriptionService;
use App\Enums\UserPreference;
use App\Models\Achievement;
use App\Models\Comment;
use App\Models\Game;
use App\Models\Leaderboard;
use App\Models\Ticket;
use App\Models\User;
use App\Notifications\Auth\ValidateUserEmailNotification;
use App\Notifications\Community\CommunityActivityNotification;

function sendValidationEmail(User $user, string $email): bool
{
    // This generates and stores (and returns) a new email validation string in the DB.
    $strValidation = generateEmailVerificationToken($user);

    $user->notify(new ValidateUserEmailNotification($strValidation));

    return true;
}

function informAllSubscribersAboutActivity(
    CommentableType $commentableType,
    int $commentableId,
    User $activityAuthor,
    int $commentID,
    ?string $onBehalfOfUser = null,
): void {
    $subjectAuthor = null;
    $urlTarget = null;
    $articleTitle = '';
    $articleEmailPreference = UserPreference::EmailOn_ActivityComment;
    $subscriptionSubjectType = null;

    switch ($commentableType) {
        case CommentableType::Game:
            $game = Game::with('system')->find($commentableId);
            if (!$game) {
                return;
            }

            $articleTitle = "{$game->title} ({$game->system->name})";
            $urlTarget = route('game.show', ['game' => $game, 'tab' => 'community']);
            $articleEmailPreference = UserPreference::EmailOn_AchievementComment;
            $subscriptionSubjectType = SubscriptionSubjectType::GameWall;
            break;

        case CommentableType::Achievement:
            $achievement = Achievement::with(['game', 'developer'])->find($commentableId);
            if (!$achievement) {
                return;
            }

            $articleTitle = "{$achievement->title} ({$achievement->game->title})";
            $urlTarget = route('achievement.show', $achievement);
            $subjectAuthor = $achievement->developer;
            $articleEmailPreference = UserPreference::EmailOn_AchievementComment;
            $subscriptionSubjectType = SubscriptionSubjectType::Achievement;
            break;

        case CommentableType::User:  // User wall
            $wallUser = User::find($commentableId);
            if (!$wallUser) {
                return;
            }

            $articleTitle = $wallUser->display_name;
            $urlTarget = route('user.show', $wallUser);
            $subjectAuthor = $wallUser;
            $articleEmailPreference = UserPreference::EmailOn_UserWallComment;
            $subscriptionSubjectType = SubscriptionSubjectType::UserWall;
            break;

        case CommentableType::Leaderboard:  // Leaderboard
            // note: cannot currently explicitly subscribe to leaderboard
            $leaderboard = Leaderboard::with('game')->find($commentableId);
            if (!$leaderboard) {
                return;
            }

            $articleTitle = "{$leaderboard->title} ({$leaderboard->game->title})";
            $urlTarget = "leaderboardinfo.php?i=$commentableId";
            $articleEmailPreference = UserPreference::EmailOn_AchievementComment;
            $subscriptionSubjectType = SubscriptionSubjectType::Leaderboard;
            break;

        case CommentableType::AchievementTicket:  // Ticket
            $ticket = Ticket::with(['ticketable.game', 'reporter'])->find($commentableId);
            if (!$ticket || !$ticket->ticketable) {
                return;
            }

            $ticketable = $ticket->getTicketableModel();
            $articleTitle = "{$ticketable->getTicketableTitle()} ({$ticketable->getTicketableGame()->title})";
            $urlTarget = route('ticket.show', ['ticket' => $ticket->id]);
            $subjectAuthor = $ticket->reporter;
            $articleEmailPreference = UserPreference::EmailOn_TicketActivity;
            $subscriptionSubjectType = SubscriptionSubjectType::AchievementTicket;
            break;

        default:
            break;
    }

    if ($subscriptionSubjectType === null) {
        return;
    }

    // some comments are generated by the user "Server" on behalf of other users whom we don't want to notify
    if ($onBehalfOfUser !== null) {
        $activityAuthor = User::whereName($onBehalfOfUser)->first();
    }

    $payload = null;
    if ($commentID > 0) {
        // For supported comment types, use the intelligent redirect route that
        // handles pagination correctly. For other types (like tickets), append the anchor directly.
        if ($commentableType->supportsCommentRedirect()) {
            $urlTarget = route('comment.show', ['comment' => $commentID]);
        } else {
            $urlTarget .= "#comment_$commentID";
        }

        $comment = Comment::find($commentID);
        if ($comment) {
            // this is similar to the logic for being able to create a ticket. the user account
            // must be at least 24 hours old and have at least five minutes on playtime. if not,
            // we don't trust the user and shouldn't broadcast their message to all subscribers
            // as mass emails with junk content could get us flagged for spamming.
            if ($comment->user->created_at->diffInDays() >= 1
                && ($comment->user->playerSessions()->where('duration', '>', 5)->exists()
                    || $comment->user->playerAchievementSets()->where('time_taken', '>', 5)->exists())) {
                $payload = nl2br($comment->body);
            }
        }
    }

    $subscriptionService = new SubscriptionService();
    $subscribers = $subscriptionService->getSegmentedSubscriberIds($subscriptionSubjectType, $commentableId, $subjectAuthor?->id);

    $notificationService = new SubscriptionNotificationService();
    $notificationService->queueNotifications($subscribers['implicitlySubscribedNotifyLater'],
        $subscriptionSubjectType, $commentableId, $commentID, $articleEmailPreference);

    $emailTargets = $notificationService->getEmailTargets(
        array_merge($subscribers['explicitlySubscribed'], $subscribers['implicitlySubscribedNotifyNow']),
        $articleEmailPreference);

    foreach ($emailTargets as $subscriber) {
        $isThirdParty =
            ($activityAuthor === null || !$activityAuthor->is($subscriber))
            && ($subjectAuthor === null || !$subjectAuthor->is($subscriber));

        sendActivityEmail(
            $subscriber,
            $commentableId,
            $activityAuthor,
            $commentableType,
            $articleTitle,
            $urlTarget,
            $isThirdParty,
            $payload,
        );
    }
}

function sendActivityEmail(
    User $user,
    int $actID,
    ?User $activityCommenter,
    CommentableType $commentableType,
    string $articleTitle,
    string $urlTarget,
    bool $threadInvolved = false,
    ?string $payload = null,
): bool {
    if (
        $user->is($activityCommenter)
        || $user->isGone()
        || $user->isInactive()
        || empty($user->email)
    ) {
        return false;
    }

    $user->notify(new CommunityActivityNotification(
        $actID,
        $activityCommenter?->display_name ?? $activityCommenter?->username,
        $commentableType,
        $articleTitle,
        $urlTarget,
        $threadInvolved,
        $payload,
    ));

    return true;
}
