### Latest client
# curl -X POST --location "http://{{host}}/dorequest.php" \
#    -H "Content-Type: application/x-www-form-urlencoded" \
#    -d "r=latestclient&e={{emulator}}"
POST {{host}}/dorequest.php
Content-Type: application/x-www-form-urlencoded

r=latestclient&e={{emulator}}

### Latest integration
# curl -X POST --location "http://{{host}}/dorequest.php" \
#    -H "Content-Type: application/x-www-form-urlencoded" \
#    -d "r=latestintegration"
POST {{host}}/dorequest.php
Content-Type: application/x-www-form-urlencoded

r=latestintegration

### Login. Retrieve and save token.
# curl -X POST --location "http://{{host}}/dorequest.php" \
#    -H "Content-Type: application/x-www-form-urlencoded" \
#    -d "u={{apiUser}}&p={{password}}&r=login"
POST {{host}}/dorequest.php
Content-Type: application/x-www-form-urlencoded

u={{apiUser}}&p={{password}}&r=login

> {% client.global.set("token", response.body.json.Token); %}

### Game ID
# curl -X POST --location "http://{{host}}/dorequest.php" \
#    -H "Content-Type: application/x-www-form-urlencoded" \
#    -d "u={{apiUser}}&t={{token}}&r=gameid&m={{gameHash}}"
POST {{host}}/dorequest.php
Content-Type: application/x-www-form-urlencoded

u={{apiUser}}&t={{token}}&r=gameid&m={{gameHash}}

###
