#!/bin/sh
# exit on error
set -e

printf "\n⏳ composer lint\n"
vendor/bin/pint --test

printf "\n⏳ composer analyse\n"
vendor/bin/phpstan analyse --memory-limit 512M

printf "\n⏳ npm run lint:eslint\n"
npx eslint --quiet

printf "\n⏳ npm run test\n"
npm run test

printf "\n⏳ composer test\n"
# Check the OS. Windows does not support the --parallel flag.
if [ "$(uname)" = "Linux" ] || [ "$(uname)" = "Darwin" ]; then
  # Use --parallel on macOS and Linux.
  vendor/bin/phpunit --parallel
else
  # If neither of those are detected, don't use --parallel.
  vendor/bin/phpunit
fi


printf "\n✅ pre-push OK\n\n"
