#!/bin/sh

printf "\n⏳ composer lint" && \
vendor/bin/php-cs-fixer fix --verbose --dry-run --show-progress=none && \
printf "\n⏳ npm lint" && \
npm run lint && \
printf "\n⏳ composer analyse" && \
vendor/bin/phpstan analyse --memory-limit 512M --no-progress && \
printf "\n✅ pre-push hook\n\n"
