export type PlayableListSortOrder =
  | '-displayOrder'
  | '-points'
  | '-rank'
  | '-title'
  | '-type'
  | '-wonBy'
  | 'active'
  | 'displayOrder'
  | 'normal'
  | 'points'
  | 'rank'
  | 'title'
  | 'type'
  | 'wonBy';
