name: Create Automated Crowdin Translations PR

on:
  schedule:
    - cron: '0 0 * * 3' # 00:00 UTC on Wednesday
  workflow_dispatch: # Allow the workflow to be manually dispatched.

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-translations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10.17
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Download translations
        run: pnpm crowdin:download
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      
      - name: Check for changes
        id: git-check
        run: |
          git add -N .  # Stage all files to include untracked files in diff
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: steps.git-check.outputs.changes == 'true'
        with:
          commit-message: 'chore: sync translations from Crowdin'
          title: 'chore: sync translations from Crowdin'
          body: |
            This PR was automatically created by _crowdin-download.yml_.
            
            It synchronizes our translations with the latest versions from Crowdin.
          branch: chore/sync-translations
          base: master
          delete-branch: true