on:
#  push:
#    paths:
#      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
      - name: Install
        run: composer install
      - name: Lint
        run: composer lint

  phstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
      - name: Install
        run: composer install
      - name: Analyse
        run: composer analyse
